parameters:
#    ladensia_admin.example.class: Ladensia\AdminBundle\Example

services:
#    ladensia_admin.example:
#        class: %ladensia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
