parameters:
#    ladensia_email.example.class: Ladensia\EmailBundle\Example

services:
#    ladensia_email.example:
#        class: %ladensia_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
