parameters:
#    ladensia_support.example.class: Ladensia\SupportBundle\Example

services:
#    ladensia_support.example:
#        class: %ladensia_support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
