imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    default_locale: %locale%
    translator:      { fallback: %locale% }
    secret:          %secret%
#    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
#        default_locale: %locale%
#        auto_start:     true

# Twig Configuration
twig:
    debug:            1
    strict_variables: %kernel.debug%
    
services:
    debug.twig.extension:
        class: Twig_Extensions_Extension_Debug
        tags: [{ name: 'twig.extension' }]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
      connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                unix_socket: /tmp/mysql.sock
#            webshop:              
#                driver:   %database_driver%
#                host:     %database_host%
#                port:     %database_port%
#                dbname:   %webshop.database_name%
#                user:     %database_user%
#                password: %database_password%
#                unix_socket: /tmp/mysql.sock
#                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
#    secure_controllers:  true
    secure_all_services: false
    
# my services

services:
    my.common.service:
        class: Ladensia\AdminBundle\Services\CommonController
        arguments:
            container: "@service_container"
            
    image.service:
        class: Ladensia\CoreBundle\Services\ImageService
        arguments:
            container: "@service_container"
    
    product.manager:
        class: Ladensia\Store\ProductBundle\Entity\ProductManager
        arguments:
            container: "@service_container"
            em: "@doctrine.orm.entity_manager"
    
    category.manager:
        class: Ladensia\Store\ProductBundle\Entity\CategoryManager
        arguments:
            container: "@service_container"
            em: "@doctrine.orm.entity_manager"
    
    cart.manager:
        class: Ladensia\Store\CartBundle\Entity\CartManager
        arguments:
            container: "@service_container"
            em: "@doctrine.orm.entity_manager"
            
    xmlapi.service:
        class: Ladensia\CoreBundle\Services\XmlApiService
        arguments:
            container: "@service_container"

    debug.twig.extension:
        class: Twig_Extensions_Extension_Debug
        tags: [{ name: 'twig.extension' }]

fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Ladensia\UserBundle\Entity\User
