security:
    encoders:
        Ladensia\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
                id: fos_user.user_manager

    firewalls:
        admin:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login_check
                use_forward:    false
                always_use_default_target_path: false
                default_target_path:            /admin
                target_path_parameter:          _target_path
                use_referer:                    false
                failure_path:   null
                use_referer:    true
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous: ~
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:       fos_userbundle

    access_control:
          - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }
          - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
