parameters:
#    ladensia_connection.example.class: Ladensia\ConnectionBundle\Example

services:
#    ladensia_connection.example:
#        class: %ladensia_connection.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
